"""Guard against data-destroying Alembic migrations (#89).

CI runs ``alembic upgrade head`` against an EMPTY database. A ``drop_column``
in ``upgrade()`` therefore destroys nothing in CI and every test passes, while
the same migration run against the real database is irreversible.

This test reads the migration files themselves instead of running them, so it
is not fooled by the empty database. It fails when ``upgrade()`` performs a
destructive operation that has not been explicitly acknowledged in the file.

It is structural, not semantic: it cannot tell a safe drop from a catastrophic
one. All it does is refuse to let a destructive operation reach main without a
human having typed a sentence saying they meant it.

See docs/runbooks/migrations.md.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

VERSIONS = Path(__file__).resolve().parents[1] / "alembic" / "versions"
MIGRATIONS = sorted(VERSIONS.glob("*.py"))

# Operations that succeed silently on a populated table and lose data.
DESTRUCTIVE_CALLS = {"drop_column", "drop_table", "drop_constraint"}

# Raw SQL hides from the call check above: op.execute("DROP ...").
# UPDATE is deliberately absent - backfills are the fix, not the problem.
RAW_SQL_VERBS = ("drop ", "delete ", "truncate ")

# alter_column(nullable=False) is deliberately NOT flagged: on a populated
# table Postgres aborts the transaction, which is a loud, harmless failure.

ACK = "# migration-safety: reviewed"


def _upgrade_function(tree: ast.Module) -> ast.FunctionDef | None:
    """Return the module-level upgrade() function, if present.

    Scoping to upgrade() is the whole trick. Every autogenerated downgrade()
    is nothing but drops, so a naive grep would flag every migration ever
    written and the guard would be ignored within a week.
    """
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "upgrade":
            return node
    return None


def _docstring_node(fn: ast.FunctionDef) -> ast.Constant | None:
    if fn.body and isinstance(fn.body[0], ast.Expr):
        value = fn.body[0].value
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            return value
    return None


def destructive_findings(fn: ast.FunctionDef) -> list[tuple[int, str]]:
    """Return (line number, description) for each destructive op in fn."""
    findings: list[tuple[int, str]] = []
    skip = _docstring_node(fn)

    for node in ast.walk(fn):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            name = node.func.attr
            if name in DESTRUCTIVE_CALLS:
                findings.append((node.lineno, f"op.{name}()"))
            elif name == "alter_column":
                if any(kw.arg == "type_" for kw in node.keywords):
                    findings.append(
                        (node.lineno, "op.alter_column(type_=...) - casts can round or truncate")
                    )
        elif isinstance(node, ast.Constant) and isinstance(node.value, str) and node is not skip:
            lowered = node.value.lower()
            for verb in RAW_SQL_VERBS:
                if verb in lowered:
                    findings.append((node.lineno, f"raw SQL containing {verb.strip().upper()}"))

    return sorted(set(findings))


def test_migration_files_exist() -> None:
    """A guard that scans an empty list passes for the wrong reason."""
    assert MIGRATIONS, f"no migration files found under {VERSIONS} - this guard is not running"


def test_detector_catches_a_known_bad_migration() -> None:
    """The detector itself must be able to fail, or it proves nothing."""
    bad = (
        "def upgrade():\n"
        '    """Rename the column."""\n'
        '    op.add_column("visit", sa.Column("actual_duration_min", sa.Integer()))\n'
        '    op.drop_column("visit", "actual_minutes")\n'
    )
    fn = _upgrade_function(ast.parse(bad))
    assert fn is not None
    assert [what for _, what in destructive_findings(fn)] == ["op.drop_column()"]


def test_detector_ignores_a_safe_migration() -> None:
    """And it must stay quiet on the safe shape, or it will be ignored."""
    good = (
        "def upgrade():\n"
        '    op.alter_column("visit", "actual_minutes",'
        ' new_column_name="actual_duration_min")\n'
        "\n"
        "def downgrade():\n"
        '    op.drop_column("visit", "something")\n'
    )
    fn = _upgrade_function(ast.parse(good))
    assert fn is not None
    assert destructive_findings(fn) == []


@pytest.mark.parametrize("path", MIGRATIONS, ids=lambda p: p.name)
def test_destructive_operations_are_acknowledged(path: Path) -> None:
    source = path.read_text(encoding="utf-8")
    fn = _upgrade_function(ast.parse(source))
    assert fn is not None, f"{path.name} has no upgrade() function"

    findings = destructive_findings(fn)
    if not findings or ACK in source:
        return

    listed = "\n".join(f"  line {line}: {what}" for line, what in findings)
    pytest.fail(
        f"{path.name} destroys data in upgrade() without an acknowledgement.\n\n"
        f"{listed}\n\n"
        "CI migrates an EMPTY database, so this destroyed nothing here. On a\n"
        "database with real rows it may be irreversible.\n\n"
        "If that is a mistake, see docs/runbooks/migrations.md - a rename wants\n"
        "op.alter_column(new_column_name=...), not drop + add.\n\n"
        "If it is intentional: dump first (python scripts/backup.py), then add a\n"
        "line like this anywhere in the migration file:\n\n"
        f"    {ACK} - dropping legacy array columns, see #98\n",
        pytrace=False,
    )
