"""initial schema

Revision ID: 028e593d22c5
Revises:
Create Date: 2026-09-01 09:23:34.073741

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "028e593d22c5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breed",
        sa.Column("breed_id", sa.Integer(), nullable=False),
        sa.Column("name_de", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("default_coat_type", sa.String(), nullable=True),
        sa.Column("default_hair_or_fur", sa.String(), nullable=True),
        sa.Column("typical_size_band", sa.String(), nullable=True),
        sa.Column("base_groom_minutes", sa.Integer(), nullable=True),
        sa.Column("matting_risk", sa.Integer(), nullable=True),
        sa.Column("blows_coat", sa.Boolean(), nullable=True),
        sa.Column("recommended_interval_days", sa.Integer(), nullable=True),
        sa.Column("home_care_protocol", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("breed_id"),
    )
    op.create_table(
        "owner",
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("locale", sa.String(), server_default="de", nullable=False),
        sa.Column("address_area", sa.String(), nullable=True),
        sa.Column("preferred_channel", sa.String(), nullable=True),
        sa.Column("client_since", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("visit_count", sa.Integer(), nullable=True),
        sa.Column("avg_rebook_days", sa.Numeric(), nullable=True),
        sa.Column("neglect_rate", sa.Numeric(), nullable=True),
        sa.Column("cancellation_rate", sa.Numeric(), nullable=True),
        sa.Column("no_show_count", sa.Integer(), nullable=True),
        sa.Column("avg_tip_pct", sa.Numeric(), nullable=True),
        sa.Column("lifetime_value", sa.Numeric(), nullable=True),
        sa.Column("reliability_score", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "service",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("name_de", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("base_minutes", sa.Integer(), nullable=True),
        sa.Column("buffer_minutes", sa.Integer(), nullable=True),
        sa.Column("price_base", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("service_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "dog",
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("breed_id", sa.Integer(), nullable=True),
        sa.Column("breed_secondary_id", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("weight_kg", sa.Numeric(), nullable=True),
        sa.Column("coat_type", sa.String(), nullable=True),
        sa.Column("hair_or_fur", sa.String(), nullable=True),
        sa.Column("coat_density", sa.String(), nullable=True),
        sa.Column("undercoat", sa.Boolean(), nullable=True),
        sa.Column("sheds", sa.Boolean(), nullable=True),
        sa.Column("handling_score", sa.Integer(), nullable=True),
        sa.Column("fear_triggers", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("muzzle_required", sa.Boolean(), nullable=True),
        sa.Column("two_person_job", sa.Boolean(), nullable=True),
        sa.Column("temperament_notes", sa.Text(), nullable=True),
        sa.Column("skin_conditions", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("senior_flag", sa.Boolean(), nullable=True),
        sa.Column("mobility_notes", sa.Text(), nullable=True),
        sa.Column("vet_notes", sa.Text(), nullable=True),
        sa.Column("size_band", sa.String(), nullable=True),
        sa.Column("visit_count", sa.Integer(), nullable=True),
        sa.Column("avg_duration_min", sa.Numeric(), nullable=True),
        sa.Column("duration_stddev_min", sa.Numeric(), nullable=True),
        sa.Column("typical_interval_days", sa.Numeric(), nullable=True),
        sa.Column("last_visit_date", sa.Date(), nullable=True),
        sa.Column("next_due_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "handling_score IS NULL OR (handling_score >= 1 AND handling_score <= 5)",
            name="ck_dog_handling_score",
        ),
        sa.ForeignKeyConstraint(
            ["breed_id"],
            ["breed.breed_id"],
        ),
        sa.ForeignKeyConstraint(
            ["breed_secondary_id"],
            ["breed.breed_id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.owner_id"],
        ),
        sa.PrimaryKeyConstraint("dog_id"),
    )
    op.create_table(
        "visit",
        sa.Column("visit_id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("visit_date", sa.Date(), nullable=False),
        sa.Column("booked_service_id", sa.Integer(), nullable=True),
        sa.Column("booking_channel", sa.String(), nullable=True),
        sa.Column("is_emergency", sa.Boolean(), nullable=True),
        sa.Column("days_since_last", sa.Integer(), nullable=True),
        sa.Column("intake_photos", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("predicted_min_p50", sa.Integer(), nullable=True),
        sa.Column("predicted_min_p90", sa.Integer(), nullable=True),
        sa.Column("quoted_price", sa.Numeric(), nullable=True),
        sa.Column("condition_score", sa.Integer(), nullable=True),
        sa.Column("matting_locations", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("fleas_or_parasites", sa.Boolean(), nullable=True),
        sa.Column("arrived_wet_dirty", sa.Boolean(), nullable=True),
        sa.Column("actual_service_id", sa.Integer(), nullable=True),
        sa.Column("pivoted", sa.Boolean(), nullable=True),
        sa.Column("pivot_reason", sa.Text(), nullable=True),
        sa.Column("shaved_down", sa.Boolean(), nullable=True),
        sa.Column("actual_minutes", sa.Integer(), nullable=False),
        sa.Column("final_price", sa.Numeric(), nullable=True),
        sa.Column("tip", sa.Numeric(), nullable=True),
        sa.Column("add_ons", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("what_surprised_me", sa.Text(), nullable=True),
        sa.Column("behaviour_this_visit", sa.Integer(), nullable=True),
        sa.Column("after_photos", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("cancelled_hours_before", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('completed', 'cancelled', 'no_show')",
            name="ck_visit_status",
        ),
        sa.CheckConstraint(
            "behaviour_this_visit IS NULL OR "
            "(behaviour_this_visit >= 1 AND behaviour_this_visit <= 5)",
            name="ck_visit_behaviour_this_visit",
        ),
        sa.CheckConstraint(
            "condition_score IS NULL OR (condition_score >= 0 AND condition_score <= 5)",
            name="ck_visit_condition_score",
        ),
        sa.ForeignKeyConstraint(
            ["actual_service_id"],
            ["service.service_id"],
        ),
        sa.ForeignKeyConstraint(
            ["booked_service_id"],
            ["service.service_id"],
        ),
        sa.ForeignKeyConstraint(
            ["dog_id"],
            ["dog.dog_id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owner.owner_id"],
        ),
        sa.PrimaryKeyConstraint("visit_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visit")
    op.drop_table("dog")
    op.drop_table("service")
    op.drop_table("owner")
    op.drop_table("breed")
    # ### end Alembic commands ###
