"""add query indexes

Revision ID: bba4e6f67c96
Revises: 028e593d22c5
Create Date: 2026-09-02 09:35:03.090279

Indexes for common MuttMetrics query paths (issue #9):
- dog.owner_id — list dogs per owner; FK join
- dog.breed_id / breed_secondary_id — breed analytics, mixes
- visit.dog_id — dog visit history; recompute dog aggregates
- visit.owner_id — owner visit history; recompute owner aggregates
- visit.visit_date — day packing, calendar / date-range filters
- visit.booked_service_id / actual_service_id — service mix, pivot analysis

CHECK constraints for scores/status were shipped in initial schema (#8).
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bba4e6f67c96"
down_revision: str | Sequence[str] | None = "028e593d22c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_dog_breed_id", "dog", ["breed_id"], unique=False)
    op.create_index("ix_dog_breed_secondary_id", "dog", ["breed_secondary_id"], unique=False)
    op.create_index("ix_dog_owner_id", "dog", ["owner_id"], unique=False)
    op.create_index("ix_visit_actual_service_id", "visit", ["actual_service_id"], unique=False)
    op.create_index("ix_visit_booked_service_id", "visit", ["booked_service_id"], unique=False)
    op.create_index("ix_visit_dog_id", "visit", ["dog_id"], unique=False)
    op.create_index("ix_visit_owner_id", "visit", ["owner_id"], unique=False)
    op.create_index("ix_visit_visit_date", "visit", ["visit_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_visit_visit_date", table_name="visit")
    op.drop_index("ix_visit_owner_id", table_name="visit")
    op.drop_index("ix_visit_dog_id", table_name="visit")
    op.drop_index("ix_visit_booked_service_id", table_name="visit")
    op.drop_index("ix_visit_actual_service_id", table_name="visit")
    op.drop_index("ix_dog_owner_id", table_name="dog")
    op.drop_index("ix_dog_breed_secondary_id", table_name="dog")
    op.drop_index("ix_dog_breed_id", table_name="dog")
    # ### end Alembic commands ###
