"""add photo table

Revision ID: cf55d9665a46
Revises: bba4e6f67c96
Create Date: 2026-09-26 18:25:46.763378

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf55d9665a46"
down_revision: str | Sequence[str] | None = "bba4e6f67c96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("visit_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("storage_backend", sa.Text(), server_default="local", nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'profile' AND visit_id IS NULL) OR "
            "(kind IN ('intake', 'after') AND visit_id IS NOT NULL)",
            name="ck_photo_kind_visit",
        ),
        sa.CheckConstraint("kind IN ('intake', 'after', 'profile')", name="ck_photo_kind"),
        sa.CheckConstraint("byte_size > 0", name="ck_photo_byte_size"),
        sa.ForeignKeyConstraint(
            ["dog_id"],
            ["dog.dog_id"],
        ),
        sa.ForeignKeyConstraint(
            ["visit_id"],
            ["visit.visit_id"],
        ),
        sa.PrimaryKeyConstraint("photo_id"),
        sa.UniqueConstraint("storage_key", name="uq_photo_storage_key"),
    )
    op.create_index("ix_photo_dog_id_kind", "photo", ["dog_id", "kind"], unique=False)
    op.create_index("ix_photo_visit_id", "photo", ["visit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_photo_visit_id", table_name="photo")
    op.drop_index("ix_photo_dog_id_kind", table_name="photo")
    op.drop_table("photo")
    # ### end Alembic commands ###
