"""drop visit photo url arrays

Revision ID: ddf104db6342
Revises: cf55d9665a46
Create Date: 2026-10-02 08:31:23.337208

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddf104db6342"
down_revision: str | Sequence[str] | None = "cf55d9665a46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Drop legacy URL-array columns superseded by the photo table (#98)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visit", "intake_photos")
    op.drop_column("visit", "after_photos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Re-add empty array columns. Any values that existed before upgrade are gone."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visit",
        sa.Column("after_photos", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "visit",
        sa.Column("intake_photos", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


# Drop deprecated visit.intake_photos /
# after_photos; photo table is the source of truth (#98)
# migration-safety: reviewed
